### PR TITLE
Exclude Antivirus and Welcomebot for Cloud

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Exclude Antivirus and Welcomebot for Cloud. This is required for Cloud.

Please note that this PR is based on https://github.com/mattermost/mattermost-marketplace/pull/132. You can find the "real" changes in https://github.com/mattermost/mattermost-marketplace/compare/merge_master...exclude_cloud.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29147
https://mattermost.atlassian.net/browse/MM-30080

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Review by larkox — APPROVED** [review]
LGTM

**Review by aaronrothschild — APPROVED** [review]
LGTM

**Comment by DHaussermann** [comment]
@hanzei I'm not seeing the plugins hidden from Cloud as expected. Maybe the way I'm testing this is not valid?
Please advise.

Steps:
- Pulled down the branch of the marketplace
- Type `make run`
- Start an ngrok tunnel to expose port 8085
- Spun up a server with `/cloud` command (running 5.29 release and master)
- Pointed config to my local marketplace instance via ngrok
- Open plugin marketplace
**Observed**: Antivirus and WelcomeBot are visible.

**Comment by DHaussermann** [comment]
Disregard this issue ☝️ . This was caused by tests server created not actually having a `cloud` license.

**Review by DHaussermann — APPROVED** [review]
Tested and passed. 
- AntiVirus and Welcome Bot Plugins are omitted with Cloud Licence as expected
- No change when using a non-cloud license or running without a licence file
LGTM!

Thanks @hanzei for the help testing on this one.

**Pull request merged**
