### PR TITLE
Add v3.0.0 of mattermost-plugin-jira to the Marketplace

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
Add Jira version 3.0.0 to the marketplace!

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/622

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
:rocket:

**Review by levb — APPROVED** [review]

**Comment by mickmister** [comment]
@jfrerich @hanzei I think we should get https://github.com/mattermost/mattermost-marketplace/pull/116 merged before merging this, otherwise we will need to have another PR that adapts the Jira plugin's entry to include `repo_name` and `platforms` in `plugins.json`.

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-marketplace/pull/116 will require some time until it's merged into production. I think it's fine to merge this PR now.

**Review by hanzei — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Tested upgrade path - user is cautioned that there may be breaking changes
- Tested Fresh install bath 
- Check light and dark themes for icon issues
- Version is correctly shown as `3.0.0`
LGTM!

**Pull request merged**
