### PR TITLE
Add v2.0.0 of mattermost-plugin-giphy-moussetc to the Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The first update to a community plugin!

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-marketplace/issues/115

### CODE REVIEW

**Review by levb — DISMISSED** [review]

**Comment by DHaussermann** [comment]
@hanzei the link for users who want to see the release notes is broken. (404)
Screen Shot 2020-12-17 at 5 48 51 PM
Not sure how to proceed with this. The address looks correct to me `https://github.com/moussetc/mattermost-plugin-giphy/releases/tag/v2.0.0` but the actual 2.0.0 notes are sitting here `https://github.com/moussetc/mattermost-plugin-giphy/releases/tag/v2.0.0-rc1`

Can we make a change in GitHub  to resolve this?

**Comment by moussetc** [comment]
@DHaussermann  The release notes have now been made available on the correct URL.

**Comment by hanzei** [comment]
Awesome, thanks for the quick fix @moussetc :tada:

**Comment by moussetc** [comment]
Furthermore, I'll look into using https://github.com/moussetc/mattermost-plugin-giphy/releases/v2.0.0 for future versions so that the name of the tag doesn't matter, only the release name.

**Review by DHaussermann — APPROVED** [review]
Tested an passed
- Tested install path
- Tested upgrade path - with version bump warning
- Community label showing as expected
- Version correctly showing as 2.0.0
- Icon looks good in all themes
- Release note link fixed

LGTM!

Will review again if dev review adds further change.

**Pull request merged**
