### PR TITLE
Update marketplace entries for ReactDOM updates

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR updates the marketplace entries of specific plugins that are affected by the React 17 upgrade. More context here https://github.com/mattermost/mattermost-plugin-starter-template/pull/169

Plugins updated:

- `mattermost-plugin-confluence`
- `mattermost-plugin-custom-attributes`
- `mattermost-plugin-github`
- `mattermost-plugin-gitlab`
- `mattermost-plugin-jira`
- `mattermost-plugin-jitsi`
- `mattermost-plugin-todo`

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47046

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by DHaussermann** [comment]
@mickmister I see an issue here where 3 of the 6 plugin will not start. 
image
Unclear if this could be a marketplace issue or with the binary published as the release. logs suggest the correct binary was downloaded from the marketplace...
```
{"timestamp":"2022-11-16 19:43:20.360 Z","level":"error","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:79","plugin_id":"jira","wrapped_extras":"pathplugins/jira/server/dist/plugin-linux-amd64pid134errorexit status 1"}
{"timestamp":"2022-11-16 19:43:20.360 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:183","plugin_id":"jira","error":"unable to start plugin: jira: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}
```
Furthermore - This occurs when I manually download the plugin from the releases page and upload it.

Can uou please advise on next steps?

**Comment by mickmister** [comment]
@DHaussermann This PR is ready for review. Please see these steps for testing:

-----

- Create a cloud server with the following command:

`/cloud create react-dom-marketplace-test --version master --image mattermost/mm-ee-test --env MM_LOGSETTINGS_FILELEVEL=DEBUG`

- Notice plugin version numbers in marketplace:
  - confluence - v1.2.0
  - custom-attributes - v1.3.0
  - github - v2.1.2
  - gitlab - v1.5.0
  - jira - v3.2.0
  - jitsi - v2.0.0
  - todo - v0.6.0

- Install the custom attributes plugin
- Enable plugin and go to the custom attributes plugin settings
- Attempt to add a new attribute, including typing in the `teamName` select box
- Notice the webapp crashes due to ReactDOM issue

-----

- Run this marketplace PR locally, and expose with ngrok
- Set the MM server's marketplace URL to this ngrok URL
- Notice the change in marketplace version numbers:
  - confluence - v1.3.0
  - custom-attributes - v1.3.1
  - github - v2.1.4
  - gitlab - v1.5.2
  - jira - v3.2.2
  - jitsi - v2.0.1
  - todo - v0.6.1

- Upgrade custom attributes plugin
- Attempt to add a new attribute, including typing in the `teamName` select box
- Notice that the plugin functions correctly, and the webapp does not crash 
- Upgrade other plugins, and perform exploratory testing, particularly where select boxes are used

**Review by hanzei — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed.
- Tested fresh install path for all patched plugins
- Tested upgrade path for all patched plugins
- Ensured all plugins can be enabled on Cloud servers
- Sanity checked all patched plugins are running and responsive
- Checked plugins to ensure react select specifically is functional (GitHub, Jira Custom Attributes)

No issues found.

LGTM! 

Huge thanks @mickmister for the effort on this and working around the build pipeline issues that were causing blocks.

**Pull request merged**
