### PR TITLE
Add v2.2.2 of mattermost-icebreaker-plugin to the Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2020-11-23 20-55-23

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-marketplace/issues/104

### CODE REVIEW

**Comment by hanzei** [comment]
@catalintomai @DHaussermann gentle reminder to review this PR

**Review by catalintomai — APPROVED** [review]

**Review by DHaussermann — COMMENTED** [review]
I have done a round of testing?

- Plugin shows in marketplace as expected
- Install link works
- No upgrade link to test 
- `COMMUNITY` label is correctly showing
- Version number is correct at `2.2.2` 

@hanzei quick follow up on this 
1. This plugin does have an SVG icon but i it is hard to see on dark theme (this was deemed not critical for the 1st release) Do we want to use the icon or keep the generic icon for now until we see about making a change? IMO - the generic icon is fine for this release. 
2. Are you able to adjust permissions in the Ice Breaker repo for me to add new issues? the repo does not seem setup for this.

**Comment by hanzei** [comment]
1. The plugin does not seem to use an icon. This is how the slash command looks like:
Screenshot from 2020-12-04 09-13-55
2. You can create a new issue in https://github.com/monsdar/mattermost-icebreaker-plugin/issues

**Comment by hanzei** [comment]
@DHaussermann Thanks for reviewing! 

1. The plugin does not seem to use an icon. This is how the slash command looks like:
Screenshot from 2020-12-04 09-13-55
2. You can create a new issue in https://github.com/monsdar/mattermost-icebreaker-plugin/issues

**Review by DHaussermann — APPROVED** [review]
- Testing complete 
- Discussed icon issues with @hanzei 

LGTM!

**Pull request merged**
