### PR TITLE
Add v0.1.0 of mattermost-plugin-default-theme to the Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2022-01-31 16-02-21
Installed:
Screenshot from 2022-01-31 16-02-40

Thanks @mickmister for the plugin! 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-marketplace/issues/177

### CODE REVIEW

**Comment by hanzei** [comment]
@levb @DHaussermann Gentle reminder to review the PR

**Review by levb — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Gentle reminder to review this PR

**Comment by hanzei** [comment]
@DHaussermann given that this is a straight forward change, can we merge it without QA review?

**Comment by mickmister** [comment]
@DHaussermann Can you please take a look?

**Comment by hanzei** [comment]
@DHaussermann gentle bump for the time after mattercon

**Comment by mickmister** [comment]
@hanzei This is being introduced into the main product via https://github.com/mattermost/mattermost-server/issues/21181 so I think we should close this

**Comment by hanzei** [comment]
@mickmister I would still like to add it to the Marketplace, as it provides value imminently and customers don't have to wait until a server change is out.

**Review by mickmister — APPROVED** [review]

**Pull request merged**
