### PR TITLE
Unit test generate

### LINKED ISSUE #127: Write unit tests for `generate` and `add` commands
#### Summary

The CLI commands `generate` and `add` are currently not covered by unit tests.

In order to test the code, the GitHub client must be mocked in the test. You can use `gomock` as the mocking framework. If you have any questions, join the [Integrations channel](https://community.mattermost.com/core/channels/integrations) on our community server.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-29272

### PR DESCRIPTION
**Pull request by jmk-198xtsuga**
#### Summary
This pull request aims to extend unit testing coverage of the `generate`, and eventually the `add`, commands.

To isolate external online sources from the unit testing, a mock data structure is being constructed and served through `httptest` at corresponding URLs that the GitHub Client can communicate with.

To unit test functions of the marketplace plugin database generator, parameters are being mocked to target different expected real-world "problems" and also to ensure that "good" input results in the expected behaviors.

#### Ticket Link
Fixes #127 "Write unit tests for `generate` and `add` commands"

### CODE REVIEW

**Comment by jmk-198xtsuga** [comment]
Opening draft Pull Request per comment on #127 for early (and ongoing) review of work thus far:

- To isolate external HTTP traffic to GitHub (i.e. requesting repository releases and artifact info), construct a mock data structure and an instance of an `httptest` server to serve that data to the GitHub Client via a localhost connection.  Provides a limited subset of repository releases for the named repositories.
- To unit test `getReleases()` in cmd/generator/main.go, requests releases with optional pre-release flag.
- Frame set out for the other planned function unit tests, including assessment of what `getReleasePlugin()` intends to do.

**Comment by mickmister** [comment]
@jmk-198xtsuga Is this ready for review? Sorry for the wait on this

**Comment by jmk-198xtsuga** [comment]
@mickmister It's about as ready for review as I can get it, but still not "done".

I've hit a point where my off-work free time is scarce, and the next to-do's on this involve what I feel would be some heavier lifting.

The unit tests so far are targeting the smaller sub-functions on `generate()`

I'll try tomorrow to post an update about what was accomplished, what's to-do, and I'll mark the PR as ready so you can incorporate what has been done so far

**Comment by hanzei** [comment]
@jmk-198xtsuga It seems like this PR has been abandoned. Hence, I'm going to close it. Please let me know if you want to continue to work on it. Thanks for your afford!

**Comment by hanzei** [comment]
@jmk-198xtsuga It seems like this PR has been abandoned. Hence, I'm going to close it. Please let me know if you want to continue to work on it. Thanks for your afford!

**Pull request closed without merging**
