### PR TITLE
Merge master into production

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
In order to sync the two branches I did:
- Create a new branch `merge_master` from `master`
- Merged `production` into that branch
- Fixed merge conflicts
- Run `go run ./cmd/generator/ migrate` to generate the platform specific bundle URLs

The platform specific bundles are missing for Channel Recommender. I wasn't able to pin down the right yet, but I don't think it's a blocker to merging this PR.

Please review for any suspicious looking diffs.

#### Ticket Link
None

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
LGTM! Thanks so much for creating this PR!!

**Review by larkox — APPROVED** [review]
LGTM, just a small question.

**Comment by hanzei** [comment]
@DHaussermann That PR does not include any changes that haven't been reviewed already. Hence, could you just do a smoke test and check if anything suspicious comes up.

**Comment by DHaussermann** [comment]
Hi @hanzei, I have done some smoke testing. Functionally there are no problems. But there are a couple things to bring to your attention before we approve this. 
1. The issue where the download URL is not platform specific also occurs for AWS and WebEx (from what I'm seeing) - Probably still not a blocker but, I want to point it out.  
2. `hosting` field is empty for the plugins. Is this expected?

**Comment by hanzei** [comment]
1. Thanks for pointing that out. Not having a platform should not cause any issues. Once we release a new version of these plugins, a platform specific version will be available. Let me file a ticket for AWS SNS and Webex to cut a new release.
2. Yes, that is expected. Empty `hosting` means not restrictions on the hosting type.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Smoke testing did not find any functional issues
- Tested new features again to ensure platform specific binaries are downloaded and hosting can be set

LGTM!

**Pull request merged**
