### PR TITLE
Use GITHUB_TOKEN env variable instead of having the user define it

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Otherwise `make plugins.json` will fail if the user hasn't set `GITHUB_TOKEN`.

I also updated the documentation.

### CODE REVIEW

**Comment by hanzei** [comment]
@jfrerich This fixes the issue you did encounter

**Comment by hanzei** [comment]
@prapti I think the best way to debug this is to make run `make plugins.json` works fine with and without `GITHUB_TOKEN` set.

**Comment by hanzei** [comment]
@prapti Just want to touch bases: Do you have any questions about how to test this PR?

**Comment by prapti** [comment]
Hi @hanzei sorry my reviews are taking longer this time around if they're outside 5.22 since we're wrapping up some final testing for the release. I'll get on the reviews here soon. Thank you for the patience, and apologies for the lateness!

**Comment by hanzei** [comment]
Thanks for the review @prapti :+1:

**Pull request merged**
