### PR TITLE
[MM-59520] Update server model

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

I am bumping the model package in preparation for publishing Calls v1.0.0 as we made some additions to the plugin schema that will be needed.

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Review by cpoile — DISMISSED** [review]

**Review by lieut-data — APPROVED** [review]

**Review by cpoile — APPROVED** [review]

**Comment by streamer45** [comment]
Apologies, but this is the new protocol.

**Review by cpoile — APPROVED** [review]
Much more secure this way.

**Review by lieut-data — APPROVED** [review]
> Apologies, but this is the new protocol.

I guess this is marketplace specific?

**Comment by streamer45** [comment]
> > Apologies, but this is the new protocol.
> 
> I guess this is marketplace specific?

@lieut-data I was referring to repository rules which feel a bit strict (borderline painful) when it comes to simple fixes or updates that require re-approval of everyone.

**Pull request merged**
