### PR TITLE
Add mattermost plugin incident management v1.1.1

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Add mattermost plugin incident management v1.1.1

### CODE REVIEW

**Comment by cpoile** [comment]
Whoa, something went wrong. One sec.

**Comment by cpoile** [comment]
There we go, ready for review.

**Review by lieut-data — APPROVED** [review]

**Review by mickmister — APPROVED** [review]
Awesome!

**Review by prapti — APPROVED** [review]
Tested on local server.
LGTM!

**Pull request merged**
