### PR TITLE
Merge master into production

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
In order to sync the two branches I did:
- Create a new branch `merge_master`
- Merged `production` into that branch
- Fixed merge conflicts
- Run `make plugins.json` to apply https://github.com/mattermost/mattermost-marketplace/pull/68

In https://github.com/mattermost/mattermost-marketplace/pull/71 welcomebot v1.2.0 was added using `generator add` and not `make plugins.json`. This resulted into a lag of metadata. Also fixed that in this PR.

Please note that the signature of Gitlab v1.1.0 because I did had to re-generate the assets on GitHub a few weeks ago. Both the new and the old signature are valid.

I'm 0/5 if `merge_master` should also be merged into `production` to fully sync the two branches. It probably doesn't hurt. Thoughts?

#### Ticket Link
None

### CODE REVIEW

**Comment by lieut-data** [comment]
@hanzei, Ideally we'd effectively merge `production` into `master` to get `master` up-to-date, and then just merge `master` into `production` to release the new code. Would it make sense to review `merge_master` -> `master` first?

**Comment by hanzei** [comment]
@lieut-data That is an awesome command to review such PRs. Thanks!

**Comment by hanzei** [comment]
@DHaussermann To make the timeline clear: This PR has to get merged before v5.25 ships.

**Comment by DHaussermann** [comment]
@hanzei can you explain the scope of this change? Is this an infrastructure change or does it target individual plugins? My looking at the change it seems this adds functionality to mark plugins as `enterprise` or `community` is that correct?

**Comment by hanzei** [comment]
@DHaussermann Sure. This changes applies all the infrastructure change that have been accumulated over the last few month to `production`. All code changes have already been (QA-) reviewed. There are no changes to how community plugins work.

This PR introduces an `Enterprise` label to `proction`. Could you double check that the changes from https://github.com/mattermost/mattermost-marketplace/pull/79 work as described in https://github.com/mattermost/mattermost-marketplace/issues/77?

**Comment by hanzei** [comment]
MS calendar was missing it's `Enterprise` label. Fixed that in https://github.com/mattermost/mattermost-marketplace/pull/86/commits/f309290105bb141f6a6a884148bf805a4299669b.

**Comment by hanzei** [comment]
@lieut-data If this PR passes Dev and QA review without further changes required, could you please merge it and https://github.com/mattermost/mattermost-marketplace/pull/88?

**Comment by DHaussermann** [comment]
@hanzei or @lieut-data  Please merge to production before 5.25 is released release as https://github.com/mattermost/mattermost-marketplace/pull/79 for MS Calendar seems to requires these code changes.

**Pull request merged**
