### PR TITLE
Add v4.1.1 of mattermost-plugin-jira to the Marketplace

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
@fmartingr Can you please help with the review while @mickmister is out.

**Review by fmartingr — APPROVED** [review]
Content seems fine to me but I don't know how to properly test this.

**Comment by hanzei** [comment]
@Kshitij-Katiyar Did you test locally that the new version can be installed?

**Comment by Kshitij-Katiyar** [comment]
> @Kshitij-Katiyar Did you test locally that the new version can be installed?

@hanzei @fmartingr I Tested this by installing the plugin. It is working fine.

**Pull request merged**
