### PR TITLE
Add v1.3.1 of mattermost-plugin-incident-management to the Marketplace

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Add v1.3.1 of mattermost-plugin-incident-management (now called "Incident Collaboration" in the product).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32580

### CODE REVIEW

**Review by cpoile — APPROVED** [review]

**Comment by lieut-data** [comment]
@prapti, I've added you right away to this since there isn't much for developers to review here.

**Review by crspeller — APPROVED** [review]

**Comment by lieut-data** [comment]
@jaydeland, just a heads up that we're dependent on https://git.internal.mattermost.com/infrastructure/github-management/-/merge_requests/30 getting merged to rename the repository before we can list this in the marketplace.

**Review by prapti — APPROVED** [review]
Tested on local marketplace. LGTM!

**Comment by lieut-data** [comment]
We've gone ahead and manually renamed the repo, and will rely on the pending terraform merge to "keep it that way". (If it deploys by mistake and reverts to the old name, the redirect from the new name will still work.)

**Pull request merged**
