### PR TITLE
Add v2.0.1 of mattermost-plugin-github to the Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Patch release for GitHub plugin

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/435

### CODE REVIEW

**Review by levb — APPROVED** [review]
Just curious, why is this an add and not a replace?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Tested install path 
- Tested upgrade path 
- no issues enabling the plugin
- no changes to icon
- Version number correctly shows as `2.0.1`

LGTM!

**Comment by DHaussermann** [comment]
Will re-test if needed based on feedback to Lev's question.

**Comment by hanzei** [comment]
@levb mostly historical reasons. The Marketplace will only return the latest version anyway, so there is no semantic difference.

Also, appending a release makes it easier to do filtering like based on the provided server version.

**Pull request merged**
