### PR TITLE
MM-49610 - Merge master into production

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Related to #333 , merge master into production because we (calls) run the generator cmd on the production branch
- After all the commits from Master, there are two new ones: the merge commit [b248b8f](https://github.com/mattermost/mattermost-marketplace/pull/337/commits/b248b8fbb9e0af245b3dba1828bc13a849012ec9), and the `plugins.json` diff [ea51c3e](https://github.com/mattermost/mattermost-marketplace/pull/337/commits/ea51c3eb1a0792f38ce0b68ddbc661632ddd693a)
- [ea51c3e](https://github.com/mattermost/mattermost-marketplace/pull/337/commits/ea51c3eb1a0792f38ce0b68ddbc661632ddd693a) is updating the existing plugins to the new manifest (an empty `hosting` field). This way the next person to run the generator won't see all this in their diff.
- I don't _think_ this will cause any troubles with the marketplace, but correct me if I'm wrong please.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-49610

### CODE REVIEW

**Comment by lieut-data** [comment]
Swapping myself out for @mickmister, as I don't have a ton of context into recent `master` changes.

**Review by mickmister — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Nice :+1:

**Review by hanzei — APPROVED** [review]
LGTM :+1: 

would you mind merging `productio` into `master` once the PR got merged to sync the branches?

**Review by hanzei — CHANGES_REQUESTED** [review]
https://community.mattermost.com/core/pl/yiwdp5czcbyntd9ahk7etueute

**Review by streamer45 — APPROVED** [review]

**Comment by hanzei** [comment]
@cpoile Would you please merge `master` into `MM-49610-update-production-branch`?

**Comment by cpoile** [comment]
@hanzei done

**Review by hanzei — DISMISSED** [review]

**Comment by hanzei** [comment]
@DHaussermann Could you please done some smoke testing around the Marketplace to ensure nothing breaks with this update?

**Review by streamer45 — DISMISSED** [review]
Nice :+1:

**Review by hanzei — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by cpoile** [comment]
Gentle ping on this @DHaussermann, thank you!

**Comment by DHaussermann** [comment]
Sorry for the delay on this @cpoile I can make time to test this today or Monday.

Can you clarify the scope and expected behavior here? I can regression test that Calls is installable. But, the rest of the scope is unclear to me.
I see a couple changes of `github.com/mattermost/mattermost-server/v6/model` but mostly I'm curious about the `hosting` value in the manifest. Are we changing the way this works?

Please let me know if you can provide some high level test guidance.
cc @hanzei

**Comment by cpoile** [comment]
@DHaussermann No worries. From my point of view, I think we just need to test that the production marketplace will still work after this merge. The updates to model allows us to generate the `hosting` value, which was added to allow plugins to specify settings that are only for self hosted or only for cloud. 

@hanzei Do you have anything specific you'd like to see tested?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Can use Marketplace to install Calls
- Can use Marketplace to upgrade Calls from an earlier version
- Tested that hosting is still respected ex: Antivirus is not listed if licence is of type Cloud 
- Tested that SKU for Proffesional/Enterprise check is still respected
- Other various regression testing (searching, installs, theming and labels, surfacing an error if the plugin cannot start etc...)  

LGTM!

**Comment by cpoile** [comment]
Thanks @DHaussermann for the work!

**Pull request merged**
