### PR TITLE
Add mattermost plugin todo v0.4.0

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
This PR adds v0.4.0 of Todo to the Marketplace

#### Ticket Link
None

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Should there be a `Beta` label?

**Comment by larkox** [comment]
Indeed it should. Will fix.

**Review by hanzei — APPROVED** [review]
LGTM 

Merging it will have to wait until https://github.com/mattermost/mattermost-marketplace/issues/118 is resolved

**Review by jfrerich — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Tested upgrade path
- Tested install path
- Beta label is in place
- Icon and styling display as expected
- Version number correctly set to v0.4.0

LGTM!

**Comment by larkox** [comment]
@hanzei Can this be merged already? I saw you removed the Do Not Merge/Awaiting PR label, but wanted to double check.

**Comment by hanzei** [comment]
@larkox Yes, it can :+1:

**Pull request merged**
