### PR TITLE
Add v1.5.0 of mattermost-plugin-gitlab to the Marketplace

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary
This PR is for adding version `v1.5.0` of the Gitlab plugin to the Mattermost marketplace.

Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/274

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@manojmalik20 It looks like there was another marketplace PR merged since this was created. Can you please merge `production` into this branch? Thank you!

Also, I'm curious if you selected the "Allow maintainers to push to this branch" option when you opened the PR, as it seems I cannot push to the branch to perform this merge.

**Comment by manojmalik20** [comment]
> Also, I'm curious if you selected the "Allow maintainers to push to this branch" option when you opened the PR, as it seems I cannot push to the branch to perform this merge.

@mickmister Yes, that is the default setting for all the repos in our organization.

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Tested upgrade path
- Tested install path 
- Enabled plugin and spot check new features
- Tested against token expiry as a precaution
- Version number `v1.5.0` 
LGTM!

**Comment by hanzei** [comment]
@manojmalik20 can you please help out one more time?

**Comment by manojmalik20** [comment]
@hanzei This PR is ready for merging now.

**Pull request merged**
