### PR TITLE
Migrate from CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Migrate CI and CD pipeline from CircleCI to GitHub Actions.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52104

### CODE REVIEW

**Comment by hanzei** [comment]
Waiting on https://community.mattermost.com/private-core/pl/dus74mg6ginmifnosy9qiyty1e

**Comment by mickmister** [comment]
> Waiting on https://community.mattermost.com/private-core/pl/dus74mg6ginmifnosy9qiyty1e

@hanzei It seems the thread you linked to is resolved but I'm not sure https://community.mattermost.com/private-core/pl/dus74mg6ginmifnosy9qiyty1e

**Review by mickmister — COMMENTED** [review]
I gave the PR a look and have just a few questions. Overall LGTM :+1:

---

Also there's an error happening in the `cd` job running on this PR

`The function "server" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command.`

Is this something we can fully test with this PR?

**Comment by hanzei** [comment]
Closing as not a priority

**Pull request closed without merging**
