### PR TITLE
Add matterpoll v1.4.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2020-11-11 17-37-18

Tested locally and can confirm that installation works

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-marketplace/issues/129

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei I see an error when I attempt to install this on my local server from my local instance of the marketplace. The install button shows an error. 
Screen Shot 2020-11-11 at 12 55 19 PM
```
{"level":"debug","ts":1605117443.9960861,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_update_active_status"}
{"level":"debug","ts":1605117444.9935439,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"GET","url":"/api/v4/plugins/marketplace","request_id":"z3samhzh6bgmbybcngc6ne3zpo","status_code":"200"}
{"level":"error","ts":1605117452.960864,"caller":"mlog/log.go:229","msg":"Unable to store the plugin signature to the configured file store.","path":"/api/v4/plugins/marketplace","request_id":"osh897pg6jn17ja1m9spd6yzyh","ip_addr":"::1","user_id":"gfdrnf97j3f99gie1ywyq8rdow","method":"POST","err_where":"saveSignature","http_code":500,"err_details":"WriteFile: Encountered an error writing to S3., Bucket name cannot be empty"}
{"level":"debug","ts":1605117452.9609559,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"POST","url":"/api/v4/plugins/marketplace","request_id":"osh897pg6jn17ja1m9spd6yzyh","status_code":"500"}
{"level":"debug","ts":1605117456.870054,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"GET","url":"/api/v4/plugins/webapp","request_id":"g7wrmmrwybdijdjxp3rgr5ayuh","status_code":"200"}
```

The following details may be irrelevant but... From the admin side UI it seems the plugin did actually get installed but when I try to enable it, it crashes as follows:
```
{"level":"debug","ts":1605117532.923257,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"GET","url":"/api/v4/plugins/webapp","request_id":"hpnijwc38jy9pxxyzkhx8oyzzh","status_code":"200"}
{"level":"debug","ts":1605117541.2367811,"caller":"plugin/hclog_adapter.go:51","msg":"starting plugin","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64args[plugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64]"}
{"level":"debug","ts":1605117541.248972,"caller":"plugin/hclog_adapter.go:51","msg":"plugin started","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64pid31481"}
{"level":"debug","ts":1605117541.249082,"caller":"plugin/hclog_adapter.go:51","msg":"waiting for RPC address","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64"}
{"level":"debug","ts":1605117541.759617,"caller":"plugin/hclog_adapter.go:51","msg":"using plugin","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"version1"}
{"level":"debug","ts":1605117541.7596722,"caller":"plugin/hclog_adapter.go:51","msg":"plugin address","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"address/var/folders/5n/r24krwzx2g560sp89tj6cv6h0000gn/T/plugin061971868networkunixtimestamp2020-11-11T12:59:01.759-0500"}
{"level":"debug","ts":1605117541.800104,"caller":"plugin/hclog_adapter.go:51","msg":"plugin process exited","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64pid31481"}
{"level":"debug","ts":1605117541.8001568,"caller":"plugin/hclog_adapter.go:53","msg":"plugin exited","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"error","ts":1605117541.800183,"caller":"mlog/log.go:229","msg":"Unable to activate plugin","plugin_id":"com.github.matterpoll.matterpoll","error":"failed to ensure bot user: failed to set profile image: SetProfileImage: Couldn't upload profile image., "}
{"level":"debug","ts":1605117541.904844,"caller":"plugin/hclog_adapter.go:51","msg":"starting plugin","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64args[plugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64]"}
{"level":"debug","ts":1605117541.920053,"caller":"plugin/hclog_adapter.go:51","msg":"plugin started","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64pid31482"}
{"level":"debug","ts":1605117541.920189,"caller":"plugin/hclog_adapter.go:51","msg":"waiting for RPC address","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64"}
{"level":"debug","ts":1605117541.9250822,"caller":"plugin/hclog_adapter.go:51","msg":"using plugin","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"version1"}
{"level":"debug","ts":1605117541.925144,"caller":"plugin/hclog_adapter.go:51","msg":"plugin address","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"address/var/folders/5n/r24krwzx2g560sp89tj6cv6h0000gn/T/plugin703300401networkunixtimestamp2020-11-11T12:59:01.924-0500"}
{"level":"debug","ts":1605117541.9764302,"caller":"plugin/hclog_adapter.go:51","msg":"plugin process exited","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64pid31482"}
{"level":"debug","ts":1605117541.976484,"caller":"plugin/hclog_adapter.go:53","msg":"plugin exited","plugin_id":"com.github.matterpoll.matterpoll"}
{"level":"error","ts":1605117541.976508,"caller":"mlog/log.go:229","msg":"Unable to activate plugin","plugin_id":"com.github.matterpoll.matterpoll","error":"failed to ensure bot user: failed to set profile image: SetProfileImage: Couldn't upload profile image., "}
{"level":"debug","ts":1605117541.992446,"caller":"jobs/workers.go:143","msg":"Workers received config change."}
{"level":"debug","ts":1605117541.9924889,"caller":"jobs/schedulers.go:201","msg":"Schedulers received config change."}
```

**Comment by DHaussermann** [comment]
@hanzei regarding the issue above - multiple plugins are affected not just Matterpoll. Please advise if there are any changed to the marketplace in general.

**Review by catalintomai — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei Disregard issue mentioned above. Sorry this, was caused by issues with local file storage and not the download link.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Install works as expected
- Icon looks good in all themes
- `COMMUNITY` label correctly displayed
- Release testing was already done for `1.4.0`

LGTM!

**Pull request merged**
