### PR TITLE
Add v1.5.0-cloud of mattermost-plugin-zoom to the Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Add Zoom `v1.5.0-cloud` as a cloud only release.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/183

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann I'm not sure how to test this. Did you got a cloud license?

**Review by mickmister — DISMISSED** [review]
LGTM!

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
Test setup:
1. Cleared all Zoom data from my local KV store and config.json
2. Applied Cloud license 
3. Set Marketplace to production to Install Zoom 1.4.1
- Set Marketplace to this branch and confirmed 1.5.0-cloud is available
- Removed cloud license and confirmed 1.5.0-cloud is **not** available 

- Tested upgrade Path. Ensured plugin continues running when oAuth is enable. Ensured new OAuth account level is set to false so upgrade will be seamless for those using oAuth 
- Tested Fresh install path
LGTM!

**note** There is a know issue where clicking `Configure` will show you stale data until you hit refresh (no impact when navigating to the setting page manually) but this is outside the scope of Zoom.

**Comment by DHaussermann** [comment]
@hanzei Yes, I have a license but testing marketplace cases is still awkward as any data in my local config could contaminate the results. Maybe we can come up with an easier way in the future. For now, I believe I was adequate able to mimic the customer experience.

**Review by aaronrothschild — APPROVED** [review]
LGTM, Please do not merge until I update the docs today.

**Comment by hanzei** [comment]
Talked with @aaronrothschild offline. This can be merged. Docs will follow later.

**Pull request merged**
