### PR TITLE
Add v1.2.0 of mattermost-plugin-apps to the Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/378

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Comment by azigler** [comment]
I noticed that https://github.com/mattermost/mattermost-server/pull/22013 is already merged. Are we already using `v1.2.0` on new deploys? I noticed that I have `v1.2.0` in my cloud server. 🎉

Is there anything specific this PR is waiting on? No rush of course, but there are a few PRs waiting for this to be merged so just wanted to check in about it.

cc @cwarnermm @asatkinson @javaguirre @mickmister

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
This should just need @DHaussermann's look at this

**Comment by hanzei** [comment]
@DHaussermann Would you please take a look at this PR?

**Review by DHaussermann — APPROVED** [review]
Tested this PR
- Install path works
- Upgrade path works
- No changes to icon
- I did notice that the link does not point to the repo/ Maybe it needs to be updated. This is not urgent enough to block this PR. I created https://github.com/mattermost/mattermost-plugin-apps/issues/446 so we can adsress this for `1.2.1`

LGTM!

**Pull request merged**
