### PR TITLE
Add v1.2.0 of mattermost-plugin-gitlab to the Marketplace

### PR DESCRIPTION
**Pull request by iomodo**

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGMT

**Comment by jfrerich** [comment]
@hanzei, with Dylan out this week, would you be ok with a dev QA?

**Comment by hanzei** [comment]
@jfrerich Sure.

**Comment by hanzei** [comment]
Tested and passed
- Upgrade path is working as expected
- Fresh install path was tested
- Version number correctly listed as `1.2.0` 

LGTM :+1:

**Comment by jfrerich** [comment]
Thanks for the QA @hanzei :)

**Pull request merged**
