### PR TITLE
Add v0.11.0 of focalboard to the Marketplace

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Publish Focalboard (Boards) v0.10.0 to the Marketplace

### CODE REVIEW

**Review by chenilim — APPROVED** [review]

**Comment by amyblais** [comment]
@hanzei Please help prioritize reviews for this and the related PRs (needed for dot releases).

**Comment by sbishel** [comment]
Actually this one is for the 6.2 release. The others are for the dot releases. This one being most important for v0.7.5 https://github.com/mattermost/mattermost-marketplace/pull/241

**Review by hanzei — APPROVED** [review]
Out of curiosity: Why do is it required for a dot release to add the plugin release to the Marketplace? Is pre-packaging it not enough?

**Comment by sbishel** [comment]
@hanzei - My understanding is this will allow users to upgrade Boards without upgrading to 6.2. However, after discussing with @chenilim, v0.9.5 and v10.1 aren't necessary because they can upgrade to v0.11.0. v0.8.4 was necessary for those with version < 6.0 (ie. 5.37). Let me know if any of this doesn't sound right.

**Comment by hanzei** [comment]
@sbishel Got it. Yes, I was wondering about v0.9.5 and v10.1. I'm still fine with adding them, but wanted to check if they are a necessity.

**Pull request merged**
