### PR TITLE
Add mattermost plugin autolink v1.2.0

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
Please add to the marketplace.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23175

### CODE REVIEW

**Comment by jfrerich** [comment]
@hanzei.  This PR includes the custom-attributes plugin and I need to correct for that.  Just FYI, before you need to review.

**Comment by jfrerich** [comment]
Ok.  I think I know why this happened.  The `go run ./cmd/generator --database plugins.json --debug` generates the `plugins.json` file from the available releases on GitHub.  Currently, that includes `custom-attributes` `v1.2.0`.  However, this ticket (https://github.com/mattermost/mattermost-marketplace/pull/53) has not been merged and the `production` branch doesn't yet include it.  

When this happens, I'm not positive on how to proceed.  I feel like I should wait until the custom-attributes PR is merged and then `git merge` production into this branch.

**Comment by hanzei** [comment]
@jfrerich Heads up that this PR now conflicts with https://github.com/mattermost/mattermost-marketplace/pull/53

**Comment by hanzei** [comment]
@jfrerich Heads up that I merged `production` into the branch.

**Comment by hanzei** [comment]
Screenshot from 2020-04-12 07-59-32
:confused:

**Pull request merged**
