### PR TITLE
Add v1.15.1-alpha.1 of Incident Collaboration to the Marketplace

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary

Plugin cut using Matterbuild with
```
/mb cutplugin --repo mattermost-plugin-incident-collaboration --tag v1.15.1-alpha.1 --pre-release --commitSHA 66c9ee4b66a3caa570ae4c2d7cb3a38d10f7de7b
```

Changes to the Marketplace here generated with
```
go run ./cmd/generator/ add mattermost-plugin-incident-collaboration v1.15.1-alpha.1 --official --beta
```

### CODE REVIEW

**Review by iomodo — APPROVED** [review]

**Comment by agarciamontoro** [comment]
@cpoile, @crspeller: are you guys ok with this approach?

**Comment by cpoile** [comment]
I guess so. It has the `--beta` tag, so it will have the beta pill, right? We will cut an `alpha.2` later with the new RHS changes anyway for community, right?

**Review by cpoile — APPROVED** [review]

**Comment by agarciamontoro** [comment]
> We will cut an alpha.2 later with the new RHS changes anyway for community, right?

But this is based off your `revert-db-changes` branch, @cpoile. Are we merging that into master? Not before we know that's the issue, right?

In any case, we will cut a new release, but not publish it in the marketplace. My idea here was to completely remove this release (I think reverting this PR would be enough) as soon as SRE can test it.

**Comment by cpoile** [comment]
@agarciamontoro definitely don't merge `revert-db-change` (`66c9ee4`) to master. :)

**Comment by agarciamontoro** [comment]
Sorry for the forced push, this is going to be merged to `private-beta` now.

**Review by cpoile — APPROVED** [review]

**Pull request merged**
